FILES([
    SERVER.public+'/css/reset.css',
    SERVER.public+'/css/common_pc.css',
    '/css/style.css',
    SERVER.public+'/lib/jszip/jszip.js',
    SERVER.public+'/lib/jszip/jszip-utils.js',
    SERVER.public+'/lib/jszip/fileSaver.js',
    SERVER.public+'/js/modules.js',
    '/js/script.js',
]);